### ISSUE TITLE
Support Hotkey for launching Qnotero

### ISSUE THREAD

**Issue by gyger** [ealbiter/qnotero#10]
It would be very nice if there is some kind of HotKey that could be used to launch Qnotero from the taskbar.

**Comment by element4l** [comment]
This seems like it should be a default feature. In fact I'm surprised that invoking it by clicking the tray icon was chosen over a hotkey to begin with. Support this feature request. Until then, I've set up a separate macro with Macro Recorder and hotkey using Hotkey macro launcher.

**Comment by ealbiter** [comment]
Hi there. Currently, you can launch Qnotero using a custom keyboard shortcut. When this shortcut is used while Qnotero is running, the main window is shown instead of creating a new instance.

**Comment by element4l** [comment]
For some reason, I have to hit the shortcut twice for it to invoke qnotero properly via this method. I guess that's fine, but my macro works the first time.
