### ISSUE TITLE
Open pdf on keypress

### ISSUE THREAD

**Issue by LioSergent** [ealbiter/qnotero#14]
Hello,
Thanks for the program, I think it fits a need.

When searching with Qnotero I can navigate relevant entries with down and up arrows.
I'd like to be able to launch the pdf (with my default viewer) by a keypress (ideally < enter >). That could also minimize Qnotero. 

Sorry if there is already an option, I could not find it.

**Comment by ealbiter** [comment]
Thank you for your suggestion. That would be an excellent addition. I will consider it.
