### ISSUE TITLE
qnotero will not run on windows

### ISSUE THREAD

**Issue by Zplusless** [ealbiter/qnotero#6]
I install qnotero on windows via binaries. When I double click the .exe file, it doesn't work .

I tried v2.1.1 and v2.1.0 and  they all fail to worl.

The OS version is windows10 1909

**Comment by hwongbaul** [comment]
I have the same problem

**Comment by ealbiter** [comment]
Sorry to hear that; I only tested those versions on Windows 7. As soon as I can get a VM with Windows 10, I will start to debug the problem

**Comment by StoltHD** [comment]
Same problem on Windows 10 Enterprise insider 19645, tested today...

Its installs, but will not run, and trying different compatibilities modes does not help...
