### ISSUE TITLE
error when building in linux ubuntu

### ISSUE THREAD

**Issue by tfaureperso** [ealbiter/qnotero#7]
Hello
when i try to build gnotero from source i have the following error
ImportError: No module named zotero_item

All the build log
sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from libqnotero.qnotero import Qnotero
  File "/tmp/qnotero/qnotero/libqnotero/qnotero.py", line 31, in <module>
    from libzotero.libzotero import LibZotero
  File "/tmp/qnotero/qnotero/libzotero/libzotero.py", line 28, in <module>
    from libzotero.zotero_item import zoteroItem as zotero_item
ImportError: No module named zotero_item

thanks in advance for your help

**Comment by ealbiter** [comment]
I have updated the install instructions since in Ubuntu and its derivatives python 2 is still the default, and qnotero needs v3.3 and above to work. Please try the new directions and let me know if they worked.
